// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZwalks.Api.Data;

#nullable disable

namespace NZwalks.Api.Migrations
{
    [DbContext(typeof(NZwalkDbContext))]
    partial class NZwalkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZwalks.Api.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6246e4b9-da4f-4e83-a778-51ac742524e2"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("84b58f3c-2e20-4809-8a5d-2a1d1c55d635"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("79a6253b-eb78-4168-988d-611a62e2ed40"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZwalks.Api.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4161cb1-52ba-413d-a8f4-bd2800efb54d"),
                            Code = "TN36",
                            Name = "Gobi",
                            RegionImageUrl = "https//gobi.com"
                        },
                        new
                        {
                            Id = new Guid("969cf319-f21a-4ff4-835b-808cb932186f"),
                            Code = "TN37",
                            Name = "Coimbatore",
                            RegionImageUrl = "https//Coimbatore.com"
                        },
                        new
                        {
                            Id = new Guid("1c43f593-c3fc-4d94-9a49-73081532ce9f"),
                            Code = "TN56",
                            Name = "Erode",
                            RegionImageUrl = "https//Erode.com"
                        },
                        new
                        {
                            Id = new Guid("bfa37282-a3df-47da-bb43-6eee646c023b"),
                            Code = "TN58",
                            Name = "Tripur",
                            RegionImageUrl = "https//Tripur.com"
                        },
                        new
                        {
                            Id = new Guid("869af7ca-0ccc-455f-b934-1bf0524c38c5"),
                            Code = "TN56",
                            Name = "Perundurai",
                            RegionImageUrl = "https//Perundurai.com"
                        });
                });

            modelBuilder.Entity("NZwalks.Api.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZwalks.Api.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZwalks.Api.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZwalks.Api.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
